# Generated by Django 5.1.6 on 2025-03-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Course_code",
            new_name="course_code",
        ),
        migrations.RemoveField(
            model_name="course",
            name="Course_name",
        ),
        migrations.AddField(
            model_name="course",
            name="course_name",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
